// Depth of field + custom kernel
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D GBufferTextureSampler3;
//   sampler2D HDRSampler;
//   float4 TexelSize;
//   float4 dofBlur;
//   float4 dofDist;
//   float4 dofProj;
//   float4 globalScreenSize;
//
//
// Registers:
//
//   Name                         Reg   Size
//   ---------------------------- ----- ----
//   globalScreenSize             c44      1
//   TexelSize                    c76      1
//   dofProj                      c77      1
//   dofDist                      c78      1
//   dofBlur                      c79      1
//   GBufferTextureSampler3       s1       1
//   HDRSampler                   s2       1
//

    ps_3_0
    def c127, 0.9999999, 1, 0, 0	// LogDepth constants
    def c1, 0, 0.212500006, 0.715399981, 0.0720999986
    def c2, 0.25, 1, 256, 0
    def c4, -0.5, -1.5, 1.5, 0.5
	
	def c14, 0.0625, 0.0322581, 0.000926, 0.000617
	def c15, -0.500, -1.500, -1.581, 0.012
	def c16, -0.477, 1.507, 1.286, 0.920
	def c17, 1.272, -0.939, -1.000, -3.000
	def c18, -2.572, -1.839, -3.162, 0.024
	def c19, -2.544, 1.878, -0.954, 3.015
	def c20, 1.000, 3.000, 2.572, 1.839
	def c21, 3.162, -0.024, 2.544, -1.878
	def c22, 0.954, -3.015, -1.500, -4.500
	def c23, -3.201, -3.501, -4.348, -1.896
	def c24, -4.743, 0.036, -4.319, 1.962
	def c25, -3.147, 3.549, -1.432, 4.522
	def c26, 0.532, 4.714, 2.403, 4.090
	def c27, 3.859, 2.759, 4.647, 0.951
	def c28, 4.632, -1.021, 3.816, -2.817
	def c29, 2.340, -4.126, 0.460, -4.721
	
    dcl_texcoord v0.xy
    dcl_2d s1
    dcl_2d s2
    texld r0, v0, s1
	// ----------------------------------------------------------------- Log2Linear -----------------------------------------------------------------
	if_ne r0.x, c127.y
		rcp r20.x, c128.x
		mul r20.x, r20.x, c128.y
		pow r20.x, r20.x, r0.x
		mul r20.x, r20.x, c128.x	// W_clip
		
		add r20.y, r20.x, -c128.x
		add r20.z, c128.y, -c128.x
		mul r20.y, r20.y, c128.y
		mul r20.z, r20.z, r20.x
		rcp r20.z, r20.z
		mul r20.w, r20.y, r20.z		// Linear depth
		
		min r0, r20.w, c127.x		// FP error hack
	endif
	// ----------------------------------------------------------------------------------------------------------------------------------------------
    add r0.y, -c77.x, c77.y
    rcp r0.y, r0.y
    mul r0.z, r0.y, c77.y
    mul r0.z, r0.z, -c77.x
    mad r0.x, c77.y, -r0.y, r0.x
    rcp r0.x, r0.x
    mul r0.y, r0.z, r0.x
	
    mov r3, c4
    texld r7.xyz, v0, s2
	
    mad r1.w, r0.z, -r0.x, c78.w // cutscene
    mad r1.w, c78.y, -r3.w, r1.w // cutscene
    max r2.w, r1.w, c1.x // cutscene
    mad r0.x, r0.z, r0.x, -c78.w
    mad r0.x, c78.y, -r3.w, r0.x
    max r1.w, r0.x, c1.x
    rcp r0.x, c78.x // cutscene
    mul r0.x, r2.w, r0.x // cutscene
    lrp r2.w, r0.x, c79.x, c79.y // cutscene
    min r0.x, c79.x, r2.w // cutscene
    rcp r0.z, c78.z
    mul r0.z, r1.w, r0.z
    lrp r1.w, r0.z, c79.z, c79.y
    min r0.z, c79.z, r1.w
    max r0.z, r0.x, r0.z // cutscene
    mul r1.w, r0.z, r0.z
	
	mov r20, c76.xyxy
	mul r20, r20, c44.y
	mov r21.xyz, r7 // center
	mov r21.w, c14.z
	if_ge r21.w, c44.w // use two rings for 1080p and below, three for above
		mul r20, r20, c14.z
		
		mad r22, r20, c15, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c16, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c17, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c18, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c19, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c20, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c21, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c22, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		
		mul r24.xyz, r21, c14.x
	else
		mul r20, r20, c14.w
		
		mad r22, r20, c15, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c16, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c17, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c18, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c19, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c20, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c21, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c22, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c23, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c24, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c25, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c26, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c27, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c28, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mad r22, r20, c29, v0.xyxy
		texldl r23.xyz, r22.xy, s2
		add r21.xyz, r21, r23
		texldl r23.xyz, r22.zw, s2
		add r21.xyz, r21, r23
		
		mul r24.xyz, r21, c14.y
	endif
	
    add r0.z, -r1.w, c2.y
	mul r3.xyz, r24, r1.w
	mad oC0.xyz, r7, r0.z, r3
    mov oC0.w, c2.y

// approximately 176 instruction slots used (14 texture, 162 arithmetic)
