// Depth of field tent filter pass
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D DOFBlurSampler;
//   float4 TexelSize;
//
//
// Registers:
//
//   Name                         Reg   Size
//   ---------------------------- ----- ----
//   TexelSize                    c76      1
//   DOFBlurSampler               s8       1
//

    ps_3_0
    def c2, 0.25, 1, 256, 0
    def c4, -0.5, -1.5, 1.5, 2.0
	
    dcl_texcoord v0.xy
    dcl_2d s8
	
	mov r0, c76
	mad r0, r0.xyxy, c4.xxww, v0.xyxy
	texld r1, r0.xy, s8
	texld r2, r0.zy, s8
	texld r3, r0.xw, s8
	texld r4, r0.zw, s8
	
	add r1, r1, r2
	add r1, r1, r3
	add r1, r1, r4
	mul oC0.xyz, r1, c2.x
    mov oC0.w, c2.y

// approximately 176 instruction slots used (14 texture, 162 arithmetic)
