//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /T ps_3_0 /E main /Fc ../source/resources/PS_BlitGamma.asm
//    ../source/resources/XenonGamma.hlsl
//
//
// Parameters:
//
//   sampler2D FrameBufferSampler;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   FrameBufferSampler s0       1
//

    ps_3_0
    def c0, 0.0773993805, 0.0549999997, 0.947867274, 0.0521326996
    def c1, 2.4000001, -0.0404499993, 4.5, 0
    def c2, 0.449999988, 1.09899998, -0.0989999995, -0.0179999992
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0
    add r1.xyz, r0, c0.y
    mul r1.xyz, r1, c0.z
    cmp r1.xyz, r0, r1, c0.w
    log r2.x, r1.x
    log r2.y, r1.y
    log r2.z, r1.z
    mul r1.xyz, r2, c1.x
    exp r2.x, r1.x
    exp r2.y, r1.y
    exp r2.z, r1.z
    mul r1.xyz, r0, c0.x
    add r0.xyz, r0, c1.y
    mov oC0.w, r0.w
    cmp r0.xyz, r0, r2, r1
    max r1.xyz, r0, c1.w
    log r2.x, r1.x
    log r2.y, r1.y
    log r2.z, r1.z
    mul r1.xyz, r2, c2.x
    exp r2.x, r1.x
    exp r2.y, r1.y
    exp r2.z, r1.z
    mad r1.xyz, r2, c2.y, c2.z
    mul r2.xyz, r0, c1.z
    add r0.xyz, r0, c2.w
    cmp oC0.xyz, r0, r1, r2

// approximately 27 instruction slots used (1 texture, 26 arithmetic)
