//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   float4 PixelOffset;
//
//
// Registers:
//
//   Name                             Reg   Size
//   -------------------------------- ----- ----
//   PixelOffset                      c238     1
//
    vs_3_0
    def c0, 2, 0, -1, 1
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1
    mad o0, v0.xyxx, c0.xxyy, c0.zzyw
    add o1, c238, v1

// approximately 2 instruction slots used
