//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 gooDeferredLightScreenSize;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   gooDeferredLightScreenSize c118     1
//

    vs_3_0
    def c0, 1, -1, 0, 0.5
    def c1, 2, 0, -1, 1
    dcl_position v0
    dcl_position o0
    dcl_texcoord o1.xy
    mad r0.xy, v0, c0, c0.zxzw
    mov r0.w, c0.w
    mad o1.xy, c118.zwzw, r0.w, r0
    mad o0, v0.xyxx, c1.xxyy, c1.zzyw

// approximately 4 instruction slots used
