//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D deferredLightDownsampleDepthSampler;
//   float4 gDeferredLightColourAndIntensity;
//   float4 gDeferredProjParams;
//   float g_fSSAOKernelScale;
//   float4 globalScreenSize;
//
//
// Registers:
//
//   Name                                Reg   Size
//   ----------------------------------- ----- ----
//   globalScreenSize                    c210      1
//   gDeferredLightColourAndIntensity    c117     1
//   gDeferredProjParams                 c119     1
//   g_fSSAOKernelScale                  c137     1
//   deferredLightDownsampleDepthSampler s1      1
//

    ps_3_0
    def c0, 37, 3, -0.25, 1
    def c1, 0.159154937, 0.5, 6.28318548, -3.14159274
    def c2, 0.75, -0.5, 0.5, 0
    def c3, -0.5, 0.5, 0, -2
    def c4, 1.00010002, 4.5, 14.9069996, 0.5
	
    // def c117     ,1, 1, 1, 1   //   gDeferredLightColourAndIntensity    
    // def c119     ,1, 1, 1, 1   //   gDeferredProjParams                 
    // def c137     ,1, 1, 1, 1   //   g_fSSAOKernelScale                  
    def c117, 1, 1, 1, 1          //   gDeferredLightColourAndIntensity    
    def c119, 0.5, 0.25, 1, 1     //   gDeferredProjParams                 
    def c137, 0.5, 1, 1, 1        //   g_fSSAOKernelScale                  
    // def c210, 1280, 720, 0.00078125, 0.01388888
	
	
    dcl_texcoord v0.xy
    dcl_2d s1
    dcl_2d s2
    texld r1, v0.xy, s1
    texld r2, v0.xy, s2
	mul oC0, r1, r2
	mov oC0.w, c0.w
	

// approximately 134 instruction slots used (9 texture, 125 arithmetic)
