//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// SSAO Blend
    ps_3_0
    def c0, 2, 3, -0.25, 1	
	
    dcl_texcoord v0.xy
    dcl_2d s3
    dcl_2d s2
    texld r1, v0.xy, s3
    texld r2, v0.xy, s2
    pow r1.y, r1.y, c0.y
    add r1.y, c0.w, -r1.y
    pow r1.x, r1.x, c0.x
    
    lrp r3.x, r1.y, r1.x, c0.w
	mul oC0, r3.x, r2
	mov oC0.w, c0.w
	
