// Stipple filter only
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D HDRSampler;
//   float4 TexelSize;
//
//
// Registers:
//
//   Name                         Reg   Size
//   ---------------------------- ----- ----
//   TexelSize                    c76      1
//   HDRSampler                   s2       1
//

    ps_3_0
    def c1, 0, 0.212500006, 0.715399981, 0.0720999986
    def c2, 0.25, 1, 256, 0
    def c4, -0.5, -1.5, 1.5, 0.5
    dcl_texcoord v0.xy
    dcl_2d s2

    mov r3, c4
    mad r4.xy, c76.xyxy, r3.xyxy, v0.xyxy
    mad r4.zw, c76.xyxy, r3.zxzx, v0.xyxy
    mad r6.xy, c76.xyxy, r3.wzwz, v0.xyxy
    mad r6.zw, c76.xyxy, r3.ywyw, v0.xyxy
    texld r7.xyz, v0, s2
    texld r3.xyz, r4.xy, s2
    texld r4.xyz, r4.zw, s2
    texld r5.xyz, r6.xy, s2
    texld r6.xyz, r6.zw, s2

    dp3 r0.x, r7, c1.yzww
    dp3 r8.x, r3, c1.yzww
    dp3 r8.y, r4, c1.yzww
    dp3 r8.z, r5, c1.yzww
    dp3 r8.w, r6, c1.yzww
    dp4 r0.z, r8, c2.x
    add r8, r8, -r0.z
    dp4 r2.w, r8, r8
    add r0.x, r0.x, -r0.z
    mad r0.x, r0.x, r0.x, -r2.w
    cmp r0.x, r0.x, c2.y, c2.w

    add r0.z, -r0.x, c2.y
    mul r1.w, r0.x, c2.x
    mul r3.xyz, r3, r1.w
    mad r3.xyz, r7, r0.z, r3
    mad r3.xyz, r4, r1.w, r3
    mad r3.xyz, r5, r1.w, r3
    mad r3.xyz, r6, r1.w, r3

    mov oC0.xyz, r3
    mov oC0.w, c2.y

// approximately 176 instruction slots used (14 texture, 162 arithmetic)
