//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    mov o0, v0
    mov o1.xy, v1

// approximately 3 instruction slots used
