#pragma once
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <subauth.h>
#include "IniReader.h"
#include "injector/injector.hpp"
#include "injector/calling.hpp"
#include "injector/hooking.hpp"
#include "includes/assembly2.hpp"
#include "injector/utility.hpp"
#include "Hooking.Patterns.h"
#include "ModuleList.hpp"
#include <thread>
#include <mutex>
#include <set>
#include <map>
#include <iomanip>
#include <array>
#include <future>
#include <d3d9.h>
